### ISSUE TITLE
Setup Rust project environment and development infrastructure - Phase 1

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/rule-agents#10]
## 📋 Overview

Set up the initial Rust project environment and development infrastructure for the RuleAgents system.

### 1. Rust Project Initialization

```bash
# Initialize Rust project (if not already done)
cargo init --name rule-agents
# or
cargo new rule-agents --bin
```

### 2. Project Structure Setup

```
rule-agents/
├── Cargo.toml                 # Project dependencies and metadata
├── Cargo.lock                 # Dependency lock file
├── README.md                  # Basic project documentation
├── .gitignore                 # Git ignore patterns
├── src/
│   ├── main.rs                # Application entry point
│   ├── lib.rs                 # Library root
│   ├── rule_engine/           # Rule engine module
│   │   ├── mod.rs
│   │   ├── rule_file.rs       # YAML loading logic
│   │   └── compiled_rule.rs   # Compiled rule structures
│   └── manager/               # Agent manager module
│       └── mod.rs
├── tests/                     # Integration tests
│   └── integration_tests.rs
├── examples/                  # Example configurations
│   ├── basic-rules.yaml
│   └── sample-usage.rs
└── docs/                      # Documentation
    └── architecture.md
```

### 3. Cargo.toml Dependencies

```toml
[package]
name = "rule-agents"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "YAML-driven agent auto-control system"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sonesuke/rule-agents"

[dependencies]
# Core dependencies
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
regex = "1.0"
anyhow = "1.0"
thiserror = "1.0"

# File watching
notify = "6.0"

# HTTP server for metrics
warp = "0.3"

# Metrics
prometheus = "0.13"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
tempfile = "3.0"
tokio-test = "0.4"
criterion = "0.5"
cargo-husky = { version = "1", default-features = false, features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy", "run-cargo-fmt"] }

[[bench]]
name = "rule_evaluation"
harness = false
```

### 4. Git Hooks Configuration

`cargo-husky` will automatically set up git hooks when you run `cargo test` for the first time. The hooks will run:

- `cargo test` - Run all tests
- `cargo clippy -- -D warnings` - Lint checks
- `cargo fmt -- --check` - Format checks

### 5. Basic CI/CD Setup (GitHub Actions)

```yaml
# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Check formatting
      run: cargo fmt -- --check

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release
```

#### .gitignore
```
/target/
Cargo.lock
*.pdb
.env
.vscode/
.idea/
*.log
```

#### Basic README.md
```markdown
# RuleAgents

YAML-driven agent auto-control system

## Quick Start

```bash
cargo build
cargo test    # This will also set up git hooks via cargo-husky
cargo run
```

### Git Hooks
Git hooks are automatically set up by `cargo-husky` when you first run `cargo test`. 
The hooks will automatically run on each commit:

- `cargo test` - Run all tests
- `cargo clippy -- -D warnings` - Lint checks  
- `cargo fmt -- --check` - Format checks

### Manual Quality Checks
You can also run these checks manually:

```bash
cargo check                    # Check compilation
cargo test                     # Run tests
cargo clippy -- -D warnings    # Lint checks
cargo fmt                      # Auto-format code
cargo fmt -- --check          # Check formatting
```

## Development

See [docs/architecture.md](docs/architecture.md) for system design.
```

## ✅ Acceptance Criteria

- [ ] Rust project successfully initializes with `cargo build`
- [ ] All specified dependencies are correctly configured in Cargo.toml
- [ ] Project structure follows Rust best practices
- [ ] **cargo-husky is configured as a dev dependency**
- [ ] **Git hooks automatically set up on first `cargo test` run**
- [ ] **Pre-commit hooks run: cargo test, cargo clippy, cargo fmt**
- [ ] CI/CD pipeline runs successfully on GitHub Actions
- [ ] Basic documentation is in place
- [ ] Development environment setup is documented
- [ ] Example YAML configuration files are created
- [ ] Integration test structure is established

## 🧪 Verification Steps

### Initial Setup
```bash
# Verify project setup
cargo check                    # Check compilation
cargo build                    # Build project
cargo test                     # Run tests + set up git hooks automatically
```

### Verify Git Hooks
```bash
# Check that hooks were created
ls -la .git/hooks/

# Test pre-commit hook
git add .
git commit -m "test commit"    # Should run hooks automatically

# If commit fails due to formatting, fix and retry:
cargo fmt
git add .
git commit -m "test commit"
```

### CI/CD Verification
- Push to GitHub and check Actions tab for green builds

### Development Tools Installation
- Install `rust-analyzer` for IDE support
- Install `cargo-edit` for dependency management: `cargo install cargo-edit`
- Install `cargo-watch` for auto-rebuilding: `cargo install cargo-watch`

### Git Configuration
- Set up branch protection rules on main branch
- Configure GitHub repository settings
- Add issue and PR templates (if desired)

## 🔗 Related

- Epic: #1
- Blocks: #3 (RuleFile implementation)
- Enables all subsequent development tasks

## 📝 Notes

- Use Rust 2021 edition for latest features
- Follow semantic versioning for releases
- Consider using `workspace` structure if project grows
- Set up proper logging infrastructure early
- Include comprehensive error handling patterns from the start
- **cargo-husky automatically manages git hooks - no additional tools required**
- **Hooks are set up automatically on first `cargo test` run**
- **All quality checks run automatically on each commit**
