### ISSUE TITLE
Redesign rule system to support flexible actions with direct key sending

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/rule-agents#36]
## Summary

Redesign the rule system to be more flexible and generic by allowing YAML rules to directly specify what keys/commands to send to the terminal, rather than having hardcoded command types.

## Current State

The current system has hardcoded command types:
```rust
pub enum CmdKind {
    Entry,  // Complex GitHub issue resolution workflow
    Resume, // Simply sends "/resume\r" to terminal
}
```

This design is inflexible and doesn't scale well for different types of automated responses.

### 1. Flexible Action Types

Replace the rigid `CmdKind` enum with flexible action types:

```yaml
rules:
  - priority: 5
    pattern: "Do you want to proceed\\?.*❯ 1\\. Yes"
    action: "send_keys"
    keys: ["1", "\r"]
  - priority: 10
    pattern: "resume"
    action: "send_keys" 
    keys: ["/resume", "\r"]
  - priority: 15
    pattern: "issue\\s+(\\d+)"
    action: "workflow"
    workflow: "github_issue_resolution"
    args: ["${1}"]  # Capture group reference
  - priority: 20
    pattern: "Continue\\?.*❯\\s*(\\d+)\\."
    action: "send_keys"
    keys: ["${1}", "\r"]  # Use captured selection number
```

### 2. New Rule Structure

```rust
#[derive(Debug, Deserialize)]
pub struct Rule {
    pub priority: u32,
    pub pattern: String,
    pub action: String,  // "send_keys" or "workflow"
    #[serde(default)]
    pub keys: Vec<String>,      // For send_keys action
    #[serde(default)]
    pub workflow: Option<String>, // For workflow action
    #[serde(default)]
    pub args: Vec<String>,      // Additional arguments
}

#[derive(Debug, Clone)]
pub enum ActionType {
    SendKeys(Vec<String>),
    Workflow(String, Vec<String>),
}
```

### 3. Updated Command Processing

```rust
async fn execute_action(&self, agent_id: &str, action: ActionType, captured_groups: Vec<String>) -> Result<()> {
    match action {
        ActionType::SendKeys(keys) => {
            self.send_keys_to_agent(agent_id, keys, captured_groups).await?;
        }
        ActionType::Workflow(workflow_name, args) => {
            self.execute_workflow(agent_id, workflow_name, args, captured_groups).await?;
        }
    }
    Ok(())
}

async fn send_keys_to_agent(&self, agent_id: &str, keys: Vec<String>, captured_groups: Vec<String>) -> Result<()> {
    if !self.test_mode {
        let backend = self.terminal_backend.backend();
        
        for key in keys {
            // Support capture group substitution
            let resolved_key = self.resolve_capture_groups(&key, &captured_groups);
            backend.send_keys(&resolved_key).await?;
            tokio::time::sleep(Duration::from_millis(50)).await; // Small delay between keys
        }
    }
    Ok(())
}

fn resolve_capture_groups(&self, template: &str, captured_groups: &[String]) -> String {
    let mut result = template.to_string();
    for (i, group) in captured_groups.iter().enumerate() {
        result = result.replace(&format!("${{{}}}", i + 1), group);
    }
    result
}
```

### 4. Workflow Registry

For complex operations like GitHub issue resolution:

```rust
pub struct WorkflowRegistry {
    workflows: HashMap<String, Box<dyn Workflow>>,
}

#[async_trait]
pub trait Workflow {
    async fn execute(&self, agent_id: &str, args: Vec<String>) -> Result<()>;
}

pub struct GitHubIssueWorkflow;

#[async_trait]
impl Workflow for GitHubIssueWorkflow {
    async fn execute(&self, agent_id: &str, args: Vec<String>) -> Result<()> {
        // Current execute_entry_command logic
        let issue_number = args.get(0).unwrap_or(&"1".to_string());
        // ... existing implementation
        Ok(())
    }
}
```

## Benefits

1. **Flexibility**: Easy to add new automated responses without code changes
2. **Simplicity**: Most common cases just need key sequences
3. **Extensibility**: Complex workflows still supported via workflow system
4. **Configuration-Driven**: All behavior defined in YAML
5. **Capture Group Support**: Dynamic responses based on pattern matches

### Auto-confirmation prompts
```yaml
- pattern: "Do you want to proceed\\?.*❯ 1\\. Yes"
  action: "send_keys"
  keys: ["1", "\r"]
```

### Dynamic selection
```yaml
- pattern: "Select option.*❯\\s*(\\d+)\\."
  action: "send_keys" 
  keys: ["${1}", "\r"]
```

### Simple commands
```yaml
- pattern: "resume"
  action: "send_keys"
  keys: ["/resume", "\r"]
```

### Complex workflows
```yaml
- pattern: "issue\\s+(\\d+)"
  action: "workflow"
  workflow: "github_issue_resolution"
  args: ["${1}"]
```

## Implementation Plan

1. **Phase 1**: Update rule file structure and parsing
2. **Phase 2**: Implement ActionType enum and execution logic
3. **Phase 3**: Add capture group substitution
4. **Phase 4**: Create workflow registry system
5. **Phase 5**: Migrate existing Entry command to workflow
6. **Phase 6**: Update tests and documentation

## Files to Modify

- `src/rule_engine/rule_file.rs` - New rule structure
- `src/rule_engine/decision.rs` - Return ActionType instead of CmdKind
- `src/manager/mod.rs` - New action execution logic
- `examples/basic-rules.yaml` - Updated rule format
- `tests/integration_tests.rs` - Test new action types
- `docs/architecture.md` - Document new design

This redesign makes the system much more powerful and flexible while maintaining simplicity for common use cases.
