### ISSUE TITLE
Refactor project to binary-only distribution

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/rule-agents#44]
## Summary

Refactor the project to be a binary-only distribution by removing unnecessary library components and example files that depend on library APIs.

### Core Library Files
- [ ] `src/lib.rs` - Library entry point (not needed for binary-only distribution)
- [ ] `src/ht_client.rs` - Legacy wrapper code that adds unnecessary complexity

### Example Files
- [ ] `examples/terminal_backend_demo.rs` - Uses library API (`use rule_agents::Ruler`)
- [ ] `examples/terminal_monitor_example.rs` - Uses library API (`use rule_agents::{MonitorConfig, TerminalOutputMonitor, TerminalSnapshot}`)

**Keep**: `examples/basic-rules.yaml` - Useful as configuration example

### 1. `Cargo.toml`
- Add explicit `[[bin]]` section
- Update description to indicate binary-only distribution
- Remove any library-related sections if present

```toml
[package]
name = "rule-agents"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "YAML-driven agent auto-control system (command-line tool)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sonesuke/rule-agents"

[[bin]]
name = "rule-agents"
path = "src/main.rs"
```

### 2. `src/main.rs`
- Add direct module declarations since `lib.rs` will be removed:

```rust
mod agent;
mod ruler;

// ... rest of the file unchanged
```

### 3. `tests/integration_tests.rs`
- Replace `use rule_agents::` imports with relative imports:

```rust
// Change from:
// use rule_agents::agent::ht_process::{HtProcessConfig, HtProcessError};
// use rule_agents::{HtProcess, Ruler};

// To:
use crate::agent::ht_process::{HtProcessConfig, HtProcessError};
use crate::{HtProcess, Ruler};
```

### 4. `README.md`
- Remove library usage examples
- Remove references to deleted `.rs` example files
- Focus documentation on binary usage only

## Benefits

1. **Simplified architecture** - Removes unnecessary abstraction layers
2. **Clearer project intent** - Binary-only distribution is more explicit
3. **Reduced maintenance burden** - Fewer files to maintain and update
4. **Remove legacy code** - `ht_client.rs` was marked as legacy and adds complexity without value

## Testing

After implementing these changes:
- [ ] Verify `cargo build --release` works correctly
- [ ] Verify `cargo test` passes with updated imports
- [ ] Verify binary functionality remains intact
- [ ] Update any CI/CD configurations if needed
