### ISSUE TITLE
Add Queue System with Periodic Triggers and Enqueue Actions

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/rule-agents#53]
# Add Queue System with Periodic Triggers and Enqueue Actions

## Overview
Implement a generic queue system that allows:
1. **Periodic execution** of commands with configurable intervals
2. **Enqueue actions** to add command execution results to named queues
3. **Queue-triggered entries** that execute when items are added to queues
4. **Task variable expansion** using `<task>` for dequeued values

## Use Case Example
Monitor GitHub issues periodically and process them automatically:

```yaml
entries:
  # Monitor GitHub issues every 30 seconds
  - name: "monitor_github_issues"
    trigger: "periodic"
    interval: "30s"
    action: "enqueue"
    queue: "github_issues"
    command: "gh issue list --state=open --json=number --jq='.[].number'"

  # Process items from github_issues queue
  - name: "process_github_issue"
    trigger: "enqueue:github_issues"
    action: "send_keys"
    keys: ["gh issue view <task>", "\r"]
```

### 1. New Trigger Types
- **Existing**: `on_start`
- **New**: `periodic` with `interval` field (supports: `30s`, `5m`, `2h`)
- **New**: `enqueue:<queue_name>` that fires when items are added to specified queue

### 2. New Action Type
- **Existing**: `send_keys`, `workflow`
- **New**: `enqueue` with `queue` and `command` fields

### 3. Variable Expansion
- **Existing**: `${1}`, `${2}` for regex capture groups
- **New**: `<task>` for dequeued values in keys

### 4. Queue Management
- Multiple named queues (FIFO)
- In-memory with optional persistence
- Thread-safe access
- Event-driven queue listeners

### Directory Structure
```
src/queue/
├── mod.rs           # Queue API and public interface
├── manager.rs       # QueueManager (multi-queue, listeners)
├── storage.rs       # Queue persistence (JSON)
└── executor.rs      # Command execution and enqueue logic
```

### Data Structures
```rust
pub enum TriggerType {
    OnStart,
    Periodic { interval: Duration },
    Enqueue { queue_name: String },
}

pub enum ActionType {
    SendKeys(Vec<String>),
    Workflow(String, Vec<String>),
    Enqueue { queue: String, command: String },
}

pub struct QueueManager {
    queues: HashMap<String, VecDeque<String>>,
    queue_listeners: HashMap<String, Vec<UnboundedSender<String>>>,
}
```

### Files to Create (4 new files)
- [ ] `src/queue/mod.rs`
- [ ] `src/queue/manager.rs` 
- [ ] `src/queue/storage.rs`
- [ ] `src/queue/executor.rs`

### Files to Update (6 files)
- [ ] `src/ruler/config.rs` - Parse enqueue action and periodic trigger
- [ ] `src/ruler/entry.rs` - Add new TriggerType variants
- [ ] `src/ruler/types.rs` - Add ActionType::Enqueue
- [ ] `src/ruler/rule.rs` - Add `<task>` variable expansion
- [ ] `src/workflow/execution.rs` - Handle enqueue action execution
- [ ] `src/main.rs` - Integrate periodic timers and queue manager

### Periodic Trigger
```yaml
- name: "periodic_task"
  trigger: "periodic"
  interval: "30s"    # Supports: s(seconds), m(minutes), h(hours)
  action: "enqueue"
  queue: "task_queue"
  command: "some_command"
```

### Queue Trigger
```yaml
- name: "queue_processor"
  trigger: "enqueue:task_queue"
  action: "send_keys"
  keys: ["process <task>", "\r"]  # <task> contains dequeued value
```

### Enqueue Action
```yaml
- name: "data_collector"
  trigger: "on_start"
  action: "enqueue" 
  queue: "collected_data"
  command: "data_collection_script.sh"
```

## Testing Requirements
- [ ] Unit tests for QueueManager operations
- [ ] Integration tests for periodic triggers
- [ ] Configuration parsing tests for new syntax
- [ ] Variable expansion tests for `<task>`

## Acceptance Criteria
1. ✅ Periodic triggers execute at specified intervals
2. ✅ Enqueue actions successfully add command results to queues
3. ✅ Queue triggers fire when items are enqueued
4. ✅ `<task>` variable properly expands to dequeued values
5. ✅ Multiple queues work independently
6. ✅ Queue persistence survives application restarts
7. ✅ Backward compatibility with existing configurations

## Implementation Notes
- Use `tokio::time::interval` for periodic execution
- Use `tokio::sync::mpsc` for queue event notifications  
- Use `tokio::process::Command` for async command execution
- Maintain FIFO ordering for queue items
- Handle command execution errors gracefully
- Support empty command results (no enqueue on empty output)

## Documentation Updates
- [ ] Update README.md with queue examples
- [ ] Update tutorial.md with periodic and queue usage
- [ ] Add configuration reference for new features
