### ISSUE TITLE
Make base port and entry concurrency configurable in config.yaml

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/rule-agents#55]
## Summary

Currently, the base port number is hardcoded to 9990 in the codebase, and entries have no concurrency control. This enhancement will make both the base port and entry-level concurrency configurable through config.yaml.

## Current State Analysis

- Base port number is hardcoded as **9990** in `src/ruler/mod.rs` in `Ruler::new()`
- `next_port: u16` field manages port allocation with auto-increment for multiple agents
- Entry execution currently has no concurrency control

### 1. Functional Requirements
- Make base port number configurable in **config.yaml**
- Make concurrency (simultaneous execution count) configurable per **entry**
- Use default values when settings are not specified
- Maintain auto-increment functionality for multiple agent creation

### 2. Configuration File Structure
```yaml
# New section
monitor:
  base_port: 8080  # Base port number (optional, default: 9990)

# Existing section (extended)
entries:
  - name: "start_mock"
    trigger: "on_start"
    action: "send_keys"
    keys: ["bash examples/mock.sh", "\r"]
    concurrency: 2  # Concurrency for this entry (optional, default: 1)
  
  - name: "simple_task"
    trigger: "on_start"
    action: "send_keys"
    keys: ["simple_script.sh", "\r"]
    # concurrency not specified = default 1

# Existing section (unchanged)
rules:
  - pattern: "..."
    # ...
```

### 3. Technical Requirements

**Configuration Structure Extension**
- Add `monitor` section to `ConfigFile` struct in `src/ruler/config.rs`
- Add `concurrency` field to `Entry` struct in `src/ruler/entry.rs`:
  ```rust
  #[derive(Debug, Deserialize)]
  pub struct MonitorConfig {
      #[serde(default = "default_base_port")]
      pub base_port: u16,
  }
  
  fn default_base_port() -> u16 { 9990 }
  fn default_entry_concurrency() -> usize { 1 }
  
  // Add to Entry struct
  pub struct Entry {
      pub name: String,
      pub trigger: String,
      pub action: String,
      // ... existing fields
      #[serde(default = "default_entry_concurrency")]
      pub concurrency: usize,  // New field, default: 1
  }
  ```

**Ruler Struct Modifications**
- Load `monitor.base_port` from config.yaml in `Ruler::new()`
- Change `next_port` initialization from hardcoded value to config value
- Add concurrency control for entry execution considering each entry's `concurrency` setting

**Entry Execution Logic Extension**
- Implement concurrency control per entry (using semaphores or counters)
- Limit parallel execution of same-name entries
- Handle waiting when concurrency limit is exceeded

**Backward Compatibility**
- No errors when new fields are undefined in existing config.yaml
- Continue operation with default values:
  - `monitor.base_port`: 9990
  - `entry.concurrency`: **1**

### 4. Impact Scope

**Files to Modify**:
- `src/ruler/config.rs` - Add MonitorConfig struct
- `src/ruler/entry.rs` - Add concurrency field to Entry struct
- `src/ruler/mod.rs` - Modify Ruler initialization, add entry concurrency control

**Test Updates**:
- Add tests for configuration loading
- Add tests for entry concurrency control
- Verify existing test functionality

**Documentation Updates**:
- README.md
- docs/tutorial.md
- config.yaml (add sample configuration)

### 5. Implementation Priority
- **High**: 
  - Basic port configuration functionality
  - Entry concurrency configuration functionality (default value 1)
- **Medium**: 
  - Error handling (invalid port numbers, concurrency values, etc.)
  - Waiting handling when concurrency limit is exceeded
- **Low**: 
  - Port range checking, conflict detection
  - Dynamic concurrency modification

## Acceptance Criteria

- [ ] Base port can be configured via `monitor.base_port` in config.yaml
- [ ] Entry concurrency can be configured via `concurrency` field per entry
- [ ] Default values work correctly when settings are omitted
- [ ] Backward compatibility maintained with existing config files
- [ ] All existing tests pass
- [ ] Documentation updated with new configuration options
