### ISSUE TITLE
Create comprehensive documentation and sample YAML - Phase 3

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/rule-agents#8]
## 📋 Overview

Create comprehensive documentation and sample YAML configurations to help users understand and effectively use the RuleAgents system.

### 1. Documentation Structure

```
docs/
├── README.md                 # Main project documentation
├── architecture.md           # System design and components
├── configuration.md          # YAML schema and configuration guide
├── getting-started.md        # Quick start guide
├── examples/                 # Sample configurations
│   ├── basic-rules.yaml
│   ├── advanced-patterns.yaml
│   └── production-config.yaml
└── api/                      # API documentation
    ├── rule-engine.md
    └── metrics.md
```

#### README.md
- Project overview and purpose
- Quick installation guide  
- Basic usage examples
- Links to detailed documentation

#### Configuration Guide
- Complete YAML schema documentation
- Rule priority explanation
- Pattern matching examples
- Command types and arguments
- Error handling behavior

#### Architecture Documentation
- System component overview
- Data flow diagrams
- Integration points
- Performance characteristics

#### Basic Rules Example
```yaml
# examples/basic-rules.yaml
rules:
  - priority: 10
    pattern: '(?i)approval required'
    command: solve-issue
    args: [auto-approve]
    
  - priority: 20
    pattern: '(?i)network error'
    command: solve-issue
    args: [reconnect]
    
  - priority: 30
    pattern: '(?i)quota exceeded'
    command: cancel
```

#### Advanced Patterns Example
```yaml
# examples/advanced-patterns.yaml
rules:
  - priority: 5
    pattern: '^ERROR:\s+Database connection failed'
    command: solve-issue
    args: [restart-db, check-credentials]
    
  - priority: 10
    pattern: '(?i)memory usage:\s+(\d+)%'
    command: solve-issue
    args: [scale-up, memory-alert]
    
  - priority: 15
    pattern: '(?i)(timeout|timed out).*after\s+(\d+)\s+seconds'
    command: solve-issue  
    args: [increase-timeout, $2]
```

## ✅ Acceptance Criteria

- [ ] Complete README with clear project explanation
- [ ] Detailed configuration documentation with all YAML options
- [ ] Architecture documentation with system diagrams
- [ ] At least 3 sample YAML configurations:
  - [ ] Basic example for beginners
  - [ ] Advanced patterns for complex scenarios  
  - [ ] Production-ready configuration template
- [ ] API documentation for all public interfaces
- [ ] Getting started guide with step-by-step instructions
- [ ] Metrics documentation explaining available metrics
- [ ] Documentation validation:
  - [ ] All code examples are tested and working
  - [ ] YAML samples are valid and functional
  - [ ] Links and references are correct
  - [ ] Spelling and grammar checked

### User-Focused Documentation
- Clear explanations for non-technical users
- Real-world use cases and scenarios
- Troubleshooting common issues
- Best practices and patterns

### Developer Documentation  
- API reference with examples
- Extension points for customization
- Contributing guidelines
- Testing instructions

### Operations Documentation
- Deployment guide
- Monitoring setup with Prometheus
- Performance tuning recommendations
- Security considerations

### Documentation Tools
- Use Markdown for broad compatibility
- Consider documentation generators (mdBook, etc.)
- Include inline code validation
- Automated link checking

### Maintenance
- Keep documentation in sync with code changes
- Version documentation with releases
- Regular review and updates
- Community contribution guidelines

## 🧪 Validation Strategy

- Test all configuration examples
- Verify installation instructions
- Validate API documentation against implementation
- User testing with documentation-only guidance

## 🔗 Related

- Epic: #1
- Depends on: #7 (Metrics implementation)  
- Blocks: #9 (Integration tests)

## 📝 Notes

- Include diagrams for system architecture
- Use consistent terminology throughout
- Provide migration guides for configuration changes
- Consider interactive examples or tutorials
